project:
  type: website
  output-dir: docs

website:
  title: "TP8 · Arquitetura de SI e Armazenamento"
  navbar:
    left:
      - href: index.qmd
        text: Slides
      - href: exercicio.qmd
        text: Exercício
